### ISSUE TITLE
Dynamically generated fields are great until you rename/move a field in Umbraco

### ISSUE THREAD

**Issue by PeteDuncanson** [rasmusjp/umbraco-graphql#1]
This is going to be a common problem and one (it cropped up in Code First days all that time) that needs thinking about up front.

Dynamically generating the schema is fantastic while developing but once that API is out in the wild and being used by the client-side (or a by another 3rd party) you can't just go changing the API by renaming fields in Umbraco as you will potentially break the front-end.

As this is a common problem there are a couple of common solutions but which one to go with I'm not sure:

* Don't change fields once they are out in the wild, this is the Facebook way, they never delete a field once its gone into production as they simply don't know who is using it.
* Allow freezing the schema by writing it to disk or similar rather than auto generating it. This is what Models Builder and uSync do once you've gone through the initial development phase you then save it to disc and thats that. How you then manage a change I don't really know, you could use redirect (see below) but at least you won't be breaking anything and regenerating will be something you can plan and manage for.
* Allow redirects for renamed fields, this is sort of how the Redirect Manager works in Umbraco now but we'd need it for fields not content. This has spaghetti code written all over it and something I'd suggest we avoid.
* Other???

We can "punt" this idea for now but its here so folks know we've at least thought about it and give them some options up above.

**Comment by PeteDuncanson** [comment]
I've had a think and done some reading around this one. I'm personally a big fan of Facebooks rule of "never delete a field" once a system has gone out into the wild, you don't know who or what might be using it. So you have to keep old fields around for backwards compat. We do this internally a lot, we might create new fields to upgrade some functionality but we would keep the old field around, move it to a "Deprecated" Tab or similar and then add some code if need to keep the field in there updated from the new fields (but we do this very rarely). I think if we treat that as the recommended best practise here then this becomes a non-issue. 

As we auto-generate the schema on start up from the doctypes in Umbraco the retired fields will still be there and available in the API so nothing breaks. If you deleted or renamed them then stuff would break if you've released your API out to the wild (such as having a 3rd party front-end team who are working with it for instance).

If you want to go deleting stuff during development time while you control the whole environment then by all means do but once "live" then the "never delete/rename a field" rule should kick in so we keep backwards compat.

Now in the GraphQL spec you can actually [mark a field as deprecated](https://facebook.github.io/graphql/draft/#sec-Deprecation) (see also [How to deprecate fields in GraphQL](https://medium.com/@kevinsimper/how-to-deprecate-fields-in-graphql-52fbd03fb9d7)) and include a description of why and what you should use instead. The field will still come back in the response but it will have additional fields attached to it so you know its deprecated, why and Graphiql will show you these. Would be lovely to be able to do that automatically somehow. I pondered being able to set the name of your "Deprecated" tab somewhere for doctypes so GraphQL would know which ones you want deprecated. If you then change the description of the field in the UI to the reason why you aren't using it then we have all the data we need. When we spin up the schema at start up we can find the deprecated fields and inject in the field description as the reason. This works double as documentation within the back office as to why you shouldn't be using those fields too! This gives us convention over configuration which I think is great (if documented enough) while working within the constraints of whats available to us.

**Comment by rasmusjp** [comment]
Hi

Just wanted to let you know that the project is moving to the [Umbraco Community](https://github.com/umbraco-community/) GitHub organisation, so we are closing all existing issues.

If you think your issue is still relevant, please feel free to reopen it.

/Rasmus
