### ISSUE TITLE
Authorisation needs adding

### ISSUE THREAD

**Issue by PeteDuncanson** [rasmusjp/umbraco-graphql#10]
We've done a lot of thought on how to do it. It breaks up nicely into a couple of chunks of effort which I guess we can link to from this one issue as and when needed.

Users need a way of controlling access to doctypes, fields and even content nodes (Umbraco users for instance can have their start node set, we should honour this). Ideally we would like to whitelist/blacklist nodes on the tree too.

For starters we hook up Authorization per field and per doctype. Checking out the docs for GraphQL.Authentication (which will need installing via Nuget) we can leverage the metadata on each GraphQL Field type to store a unique hash of the fields doctype alias, property type alias and permission, something like:

`homepage:heroBanner:can_read
`

That would give us user granular control. But then we need a list of "Claims" of access for the user hitting the site. Lets assume they are passing in a Token of some sort. We can then use that to look up that users "Claims" which GraphQL.Authentication will then automagically compare for us against all the hashes we have set per field.

We can also do the same from DocTypes too and block out a whole type.

How the settings are "set" is a work in process which I'll put in another issues tomorrow, Janae has done some wire frames of a nice back office UI to manage it. Lets assume though that we have a object in memory (loaded from a custom DB table) which has all the users in with all their settings, this is the users "Claims". Each request we would get the Claims for the passed in Token (or default to a safe default users permissions) and then pass those Claims into GraphQL.Authentication to handle.

Ideally developers might want to roll their own Authentication lookup instead of ours (I'm thinking Active Directory or something) so the authentication would have to be swappable on start up for ease but that can come later.

**Comment by PeteDuncanson** [comment]
Ok I'm getting somewhere with this so time for an update. So far I've got two database tables:

Accounts - contains information about an account that can access your data, you can create multiple account and store an access token with each, disable them, give them a friendly name etc. Currently we always ship with a Default account which has no permissions as default.

AccountSettings - this stores a row per property per doctype with a FK on AccountId. We only store rows you have access too (at least that the current thinking), if its not listed then you don't have access to it. This means if you add new fields to a doctype later they will be private by default and you will have to opt in to make them visible.

Next query is how best to pass this token around? Currently I've got it working via a query string param but GraphiQL out the box doesn't support this so I'm looking at other methods. The logical one while allowing GraphiQL to be used is to actually pass it in as part of the query but I'm not sure how this will play nice as yet so held off it.

This lead onto another line of thinking about bigger things such as CORS and JWT tokens etc. I got to thinking about how do the REST API for Umbraco handle all this stuff so went and had a poke around (https://github.com/umbraco/UmbracoRestApi/blob/master/src/Umbraco.RestApi/Security/UmbracoAuthorizationServerProvider.cs)

Seems it sort of does handle it and also doesn't. It assumes that you have to be logged in to the back office (and it gives you an endpoint to do that) and then uses all the back office logic to limit your start nodes, which sections you can see, etc. Trouble is that isn't very granular so I think we need to do more.

For now though I simply want to get the option of not being able to see everything up and running. Basically set up a default account that has default permissions and then you can opt in to allow fields to be visible. As we've got the database tables in place I'm keen to use those and I might manually add in the field names for starters until we can get a UI on it.

**Comment by rasmusjp** [comment]
Hi

Just wanted to let you know that the project is moving to the [Umbraco Community](https://github.com/umbraco-community/) GitHub organisation, so we are closing all existing issues.

If you think your issue is still relevant, please feel free to reopen it.

/Rasmus
