### ISSUE TITLE
Make GraphQL endpoints configurable

### ISSUE THREAD

**Issue by PeteDuncanson** [rasmusjp/umbraco-graphql#16]
https://github.com/rasmusjp/umbraco-graphql/blob/fbcc4e7bd2b66ff7f9606921abf6fd518de7eff9/src/Our.Umbraco.GraphQL/Web/AppBuilderExtensions.cs#L37

Currently hardcoded for convention over configuartion but we should really allow developers to over-write these.

**Comment by rasmusjp** [comment]
This is now possible by passing in a custom path to `app.UseUmbracoGraphQL()` https://github.com/rasmusjp/umbraco-graphql/blob/develop/docs/index.md#configuration
