### ISSUE TITLE
GraphiQL javascript embedded resource is not being found

### ISSUE THREAD

**Issue by PeteDuncanson** [rasmusjp/umbraco-graphql#17]
As the code stands now I can't get the GraphiQL UI to work as it appears it can't find the /umbraco/graphiql.js file referenced when we go to the /umbraco/graphql url.

Not sure what is up there as resources is not really something I do all that often let a long .html files which are a resource themselves then referencing other resources!

**Comment by rasmusjp** [comment]
Not sure why it's trying to load a local graphiql.js since the referenced resources are on CDN's https://github.com/rasmusjp/umbraco-graphql/blob/master/src/Our.Umbraco.GraphQL/Resources/graphiql.html#L32-L37

**Comment by PeteDuncanson** [comment]
Ahhh, someone's been messing with our build trying to get the frontend to handle the debug data better ;)
