### ISSUE TITLE
Setting permissions on Compositions

### ISSUE THREAD

**Issue by PeteDuncanson** [rasmusjp/umbraco-graphql#18]
A side issue raise by our work on #10 is how to manage permissions for compositions.

I think you should be able to set permissions across the site via a composition, what I mean by that is on the Navigation Base composition in the demo site I should be able set permissions on the seoMetaDescription field to be readable and that should be site wide and respected by GraphQL, any doctype with that composition and therefore that field on it will now make that field public and readable. This should only happen IF I've opted in on the composition to allow for this. 

If I only want some doctypes to have this field visible then I would set it per doctype.

Could I if I wanted to only opt out some doctypes when I want the default to be make something public. So I could select the Composition to be public and then uncheck it on the some doctype itself? That would mean that our checks would have to ensure that yes you can view this compsition and yes you can view this doctype too. 

A way around this is to do a bit of a UI fudge, we allow you to select whole Compositions via our Permissions UI (as yet un-built) and all that does is write down the permissions per doctype under the hood and we completely ignore Compositions being a "thing" when it comes to permission, its just a mental model to help make the UI managable and helpful.

**Comment by rasmusjp** [comment]
Hi

Just wanted to let you know that the project is moving to the [Umbraco Community](https://github.com/umbraco-community/) GitHub organisation, so we are closing all existing issues.

If you think your issue is still relevant, please feel free to reopen it.

/Rasmus
