### ISSUE TITLE
Supporting relations

### ISSUE THREAD

**Issue by PeteDuncanson** [rasmusjp/umbraco-graphql#19]
I suspect this is a some day maybe job but worth thinking about how to support relations between content. Tried having a go today but got myself confused. Might be a great one to discus with someone with a laptop and a drink and bounce ideas off. Looking forward to a few chats with Stephan @ uwestfest next month.

**Comment by rasmusjp** [comment]
Hi

Just wanted to let you know that the project is moving to the [Umbraco Community](https://github.com/umbraco-community/) GitHub organisation, so we are closing all existing issues.

If you think your issue is still relevant, please feel free to reopen it.

/Rasmus
