### ISSUE TITLE
"Enhance/Customise" the GraphiQL interface to allow us to do a bit more with it

### ISSUE THREAD

**Issue by PeteDuncanson** [rasmusjp/umbraco-graphql#21]
GraphiQL allows you to customise it via adding React components etc.

See: https://github.com/graphql/graphiql for details of how to customise

We will need this for a couple of reasons.

1. For authentication we are hoping to pass in some token via a header or a separate querystring param. For that to work we ideally need a UI to allow you to cut and paste in a token (and ideally save it down somewhere). Useful for #10 
2. We now have debug information coming back (which is awesome) however its pretty scary the amount it returns. Pondered having a debug summary panel that would pull that data out and make it a bit more human friendly, tabs etc. See #5

**Comment by PeteDuncanson** [comment]
Stephen has been working on this some what to see what can be done, this was the cause of #17 on our local builds. He has something working for debug info that we can build on so hoping we can have something soon

**Comment by rasmusjp** [comment]
Closing this, GraphiQL has been replaced with [GraphQL Playground](https://github.com/prisma-labs/graphql-playground)
