### ISSUE TITLE
Better error message when content by id is not found

### ISSUE THREAD

**Issue by PeteDuncanson** [rasmusjp/umbraco-graphql#28]
When searching for content By Type with an id if it can't find it then it throws a nasty error. Assume it should return null (as is the GraphQL way) and possibly an error message too?

![image](https://user-images.githubusercontent.com/1674590/46536626-fa0bbe00-c8a6-11e8-94ed-8ddf948a3e4a.png)

**Comment by PeteDuncanson** [comment]
Actually it is doing that! However the error message isn't clear that its a simple "content with that id not found" error, should be a quick one to clean up.

**Comment by rasmusjp** [comment]
Closing as this should not be a problem with the latest code
