### ISSUE TITLE
 Allow query by aliases name rather than using content(id:123)

### ISSUE THREAD

**Issue by PeteDuncanson** [rasmusjp/umbraco-graphql#3]
As it stands the auto-generated schema maps the tree structure in Umbraco. However sometimes you want to just jump to some content straight away. Use case is we have a short list of hotels and want to just get the data for the hotels in the list as hotel objects. I can do this currently using something like this (which is amazing btw):

```
{
  content(id:2755) {
    ... on HotelPage {
      name,
	  starRating,
	  price
    }
  }
}
```

However I'd prefer the syntactical sugar of something like this:

```
{
  hotelPage(id:2755) {
      name,
	  starRating,
	  price
  }
}
```

Suggest we would need to either auto add the (id:123) option to all doctypes which under the hood would do a content(id:123) and then a cast of some sort?

**Comment by rasmusjp** [comment]
This should be quite easy to implement, but right now the document types that are allowed at root are added to the query as their name.

So to avoid name collisions, I think we should prefix the ones that are allowed at root with something like `root` so you'll get `rootHotelPage: [HotelPage]` and then add all document types to the query as their type name, then the field will be like this `HotelPage(id: ID!): HotelPage`.

**Comment by rasmusjp** [comment]
PR is open in #22
