### ISSUE TITLE
Supporting members

### ISSUE THREAD

**Issue by PeteDuncanson** [rasmusjp/umbraco-graphql#37]
This was raised by someone at the USA Fest and I'd not really given it any thought. How can we access members. I've seen some commented out comments here and there about members in the code so assume its not "working" as yet. This defo needs to have authenication in there though. We shouldn't really be having members accessible via a public API. As a result until we get accounts sorted out properly then members can be on hold (see #10)

**Comment by rasmusjp** [comment]
Hi

Just wanted to let you know that the project is moving to the [Umbraco Community](https://github.com/umbraco-community/) GitHub organisation, so we are closing all existing issues.

If you think your issue is still relevant, please feel free to reopen it.

/Rasmus
