### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by mattbrailsford** [rasmusjp/umbraco-graphql#39]
I wonder if it would be a good time to look at setting up unit testing and refactoring anything that would help setting this up?

**Comment by rasmusjp** [comment]
Yes, I think it would be a good time to look into it. It's been on my todo list for a while now, but I've only got as far as creating the test project (which I've just committed and pushed).

**Comment by mattbrailsford** [comment]
I'm not actually sure the best way to do this. Maybe the
UmbracoGraphQLContext should have an interface so it can all be mocked.

Might be worth speaking to Lars (@lars-erik) for some advice.

**Comment by rasmusjp** [comment]
All the help we can get on this is much appreciated :-)

I've made some changes in the [umbraco8 branch](/rasmusjp/umbraco-graphql/tree/umbraco8) were a lot of the stuff has interfaces now (to make it work nicely with the DI), this should make it easier to do unit tests i think.

**Comment by lars-erik** [comment]
Without knowing much about the project nor graphql there's not much I can give. ;)

But a general advice is to stub as close to IO as possible to test as much as possible at once. If this is using the content cache, I'd go with the xml overriding technique with Umbraco's own tests:  
https://github.com/lars-erik/umbraco-unit-testing-samples/blob/master/Umb.Testing.Tests/SampleUmbracoTests/ContentCache_From_Xml.cs

If you're exposing a WebApi endpoint you can actually test that through HTTP hosting your endpoint from your test process. Here's an example of doing it for OData.  
https://intellitect.com/self-hosted-integration-testing-of-odata-and-webapi/  
(found from serp)

Other than that, read TDD books and just get started. :) Can't swim if you don't jump in.

**Comment by rasmusjp** [comment]
I'm closing this as I've done a larger rewrite and all the new code is tested.
