### ISSUE TITLE
How to get to parent doctypes in a "nice" way?

### ISSUE THREAD

**Issue by PeteDuncanson** [rasmusjp/umbraco-graphql#4]
In my example tree I have a layout similar to this:

```
Home
 - Destinations
	- Countries (country Doctype)
		- Greece (region Doctype )
			- Rhodes (resort Doctype)
				- Petes Amazing Hotel (hotel Doctype)
```

If I then query for my hotel and want to know what resort it is in currently I have to know about the tree structure (is this such a bad thing? I don't know but this is just an idea):

```
{
  content(id:2755) {
    ... on HotelPage {
      features,
      ancestors(includeSelf: true) {
        items {
          ... on ResortPage {
        		name   
          }
        }
      }
    }
  }
}
```

Similar to #3 I'd prefer to do something like this:

```
{
  content(id:2755) {
    ... on HotelPage {
      features,
	  resort {
		name
	  }
    }
  }
}
```

I'm not sure as yet how we might do that. The code would need to know which way to go (up or down the tree I guess) which we could do by seeing what child doctypes are allowed and many auto wiring them up? This could very quickly get into a mess if not careful and cause some crazy long graphs of possibilities or it could be amazing :)

**Comment by PeteDuncanson** [comment]
Now #23 has been done its sort of shown me the way this might be doable. I'm again not sure if its an amazing idea or not. It could very quickly lead to some crazy leaky abstractions or hardcode in the sites structure in your queries which might not be such a good idea long term.

Something to ponder maybe about how useful this might be. I can see if being done by simply looping over all the doctypes in Umbraco and adding in accessors to any allowed child doctypes pointing them to the correct GraphQLObjectTypes.

**Comment by nerfpops** [comment]
I don't think you can simplify your query to the one where you just ask for the resort. What if you have a structure with the following doctypes:

```
- DocType: A
  - DocType: B
    - DocType: A
```

Querying A from B would be problematic, because we don't know if we should fetch the children or the parents.

**Comment by rasmusjp** [comment]
Hi

Just wanted to let you know that the project is moving to the [Umbraco Community](https://github.com/umbraco-community/) GitHub organisation, so we are closing all existing issues.

If you think your issue is still relevant, please feel free to reopen it.

/Rasmus
