### ISSUE TITLE
Added config toggles to opt into different debug profiling

### ISSUE THREAD

**Issue by PeteDuncanson** [rasmusjp/umbraco-graphql#41]
As per https://github.com/rasmusjp/umbraco-graphql/issues/5#issuecomment-416446355 we currently have just the one config toggle "EnableMetrics" which will include both sets of available metrics. Would be nice to have option of include one or the other as both together can be a bit over-whelming.

This could be via a toggle or I'm also keen on allowing for this to be included on a per-query basis if possible by asking for the stats in the query itself. I'll settle for a toggle for now.

**Comment by rasmusjp** [comment]
The latest Umbraco 8 version has a config option for enabling/disabling MiniProfiler https://github.com/rasmusjp/umbraco-graphql/blob/develop/docs/index.md#configuration
