### ISSUE TITLE
Allow "flattening" of query responses to shorten object nesting?

### ISSUE THREAD

**Issue by PeteDuncanson** [rasmusjp/umbraco-graphql#43]
@JackPenney found this the other week after I raised an issue with my queries looking a bit of a mess:

https://www.fourkitchens.com/blog/development/graphql-leveler-controlling-shape-query/

If I have a heavily nested query it would be nice to make the response a little nicer to read and "hoist" the value out of the nesting and into a higher up variable. The article explains it nicely with its _get helper example.

Trouble is this is in javascript and not c# so we can't use it as is but its something to look into.

**Comment by rasmusjp** [comment]
Hi

Just wanted to let you know that the project is moving to the [Umbraco Community](https://github.com/umbraco-community/) GitHub organisation, so we are closing all existing issues.

If you think your issue is still relevant, please feel free to reopen it.

/Rasmus
