### ISSUE TITLE
Make umbraco8 the master branch

### ISSUE THREAD

**Issue by nerfpops** [rasmusjp/umbraco-graphql#49]
People are put off when they come to the repository and see the latest commit was in February. Show them there's stuff going on by moving master to umbraco7 and umbraco8 to master.

**Comment by rasmusjp** [comment]
Hi @nerfpops 

Sorry for the late reply,

I've been rewriting most of the code base over the last few months and I've pushed it to the develop branch today, which I've made the default one.
