### ISSUE TITLE
Add debug/performance stats to the bottom of the responses?

### ISSUE THREAD

**Issue by PeteDuncanson** [rasmusjp/umbraco-graphql#5]
On of the big worries with anything like this is "is it fast enough" and of course "is it optimised" or "where should I optimise". Wonder if we should return some stats on time taken to generate a query and number SQL statements etc. (if possible to get) in the response?

Could either toggle this globally via umbracoDebug or per query I guess?

**Comment by rasmusjp** [comment]
Newer versions of GraphQL for .NET added support for [Apollo Tracing](https://github.com/apollographql/apollo-tracing) which gives you per field metrics. You can see an example of the output [here](https://graphql-dotnet.github.io/docs/getting-started/metrics)

I've upgraded the project and added an option to enable metrics by passing [EnableMetrics = true](https://github.com/rasmusjp/umbraco-graphql/blob/master/samples/Website/App_Start/UmbracoEvents.cs#L14) to the `GraphQLServerOptions` in the `UseUmbracoGraphQL` call.

It might be possible to hook into the MiniProfiler and expose it as an extension as well.

**Comment by PeteDuncanson** [comment]
Was discussing with with @ste today. Great to see. He's playing with a way for format the results some more. Was thinking of an option to just "include everything" and then a GraphQL way using fragments to only pull in what your want or some helper fragments (briefStats or verboseStats or something like that).

Need to be careful we aren't duplicating effort though ;)
