### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by rasmusjp** [rasmusjp/umbraco-graphql#59]
Hey all

As some of you might know, I published this code because of [this](https://our.umbraco.com/forum/extending-umbraco-and-using-the-api/92236-getting-graphql-into-umbraco) thread on [our.umbraco.com](https://our.umbraco.com) which was started after an open space discussion at Codegarden (which I unfortunately didn't attend) and I wanted to share what I had been playing around with for some time so we didn't had to start from scratch implementing GraphQL for Umbraco.

I've tried to run the project but I really don't have the motivation to do so and as I never used the project myself in a real project (I only did it as a learning experience), I really don't think I'm the right person to continue this project, so if anyone want to take over and make it a success, please let me know.

In the coming weeks I'll transfer the project to the [Umbraco Community](https://github.com/umbraco-community) GitHub account or the [GraphQL for Umbraco](https://github.com/graphql-for-umbraco) organization (depending of the responses I get).

**Comment by mzajkowski** [comment]
Hi @rasmusjp!

We've discussed it today with the Devteam at Cogworks and **we'd like to help**. 

We're going to build some of the functionalities using GraphQL and Umbraco in the upcoming months, so we can use this as a base and/or extend it with our experience for that community usage - as it was meant to be from the beginning.

Let me know if it's still open and you haven't made any decision / agreement / assignment yet and we're happy to try to maintain it and dedicate enough amount of time to keep it alive and evolving!

Cheers and #h5yr for this amazing work! 🙌

**Comment by protherj** [comment]
Hi Rasmus,

We have been using it lately on some ProWorks projects and would also love to help.  I know @benjaminc has made a few Pull Requests to get Examine and Forms working with project and we will likely have more as we continue to use it.

Let us know how we can help and if you would like to setup a meeting sometime.


Thanks and #h5yr for the package!


-Jason

**Comment by rasmusjp** [comment]
Hi @mzajkowski and @protherj 

Awesome to see some interests in helping out with this package :)

I think it would be great if we could have meeting to talk about how we can move forward, if you can send me an email with some time suggestions I'll get a meeting setup.

**Comment by rasmusjp** [comment]
Had a great chat with @mzajkowski, @protherj and @benjaminc about the future of this project.

Here's a summary of what we talked about:

- The repository will be moved to the [Umbraco Community Org](github.com/umbraco-community/), I will still be the owner
- @mzajkowski, @protherj, @benjaminc and othrer relevant peaple will get commit rights to avoid me being the bottleneck in merging things 
- We're closing all existing issues, this doesn't mean that the issues are not relevant but we want to start with a clean board
- We created a #graphql channel on the Community Slack 
- We'll talk again in January about where we want the project to go

Thanks again y'all
