### ISSUE TITLE
Support for Unicore

### ISSUE THREAD

**Issue by rasmusjp** [rasmusjp/umbraco-graphql#69]
We should look into how we can support the upcoming .Net Core version of Umbraco.

My initial thoughts is to move the Umbraco specific parts to their own projects and be able to share as much code as possible.

**Comment by webmonger** [comment]
There seems to have been some activity around this by @benjaminc I'm interested to what the road map for this looks like and how I may be able to help. I've got the v9/dev branch up and running locally but I can't and queries working so I wondered if there where are areas could help out with?

**Comment by benjaminc** [comment]
Yes, I did start a [v9/dev branch](https://github.com/umbraco-community/umbraco-graphql/tree/v9/dev) for anyone who wants to help out.  My first step was migrating the projects, and just getting things compiling.  I haven't had time to get back to try and get things working, so if you wanted to start troubleshooting it, that would be great.  More broadly, we have a few items we are planning on working on in the project as a whole, which you can see on the issues list.  From security, to filtering, to multi-lingual support to name a few.  Feel free to dive in an pick up any of them, just throw a note on the issue saying you are working on it so if someone else wants to help they can collaborate.

**Comment by webmonger** [comment]
Great, I'll have a look and see if I can work out whats going on. Initially I could not get the example site up and running so I have a couple of changes that might help with that.

I'm not overly familiar with GraphQL but I'll see if I can work out how all the query parsers work and why data is not being returned.
