### ISSUE TITLE
Exception when running with Umbraco 9.1.2

### ISSUE THREAD

**Issue by miyagisan221b** [rasmusjp/umbraco-graphql#75]
When I add this to the project and run, I get the following error:

System.InvalidOperationException: 'A suitable constructor for type 'Our.Umbraco.GraphQL.Composing.GraphVisitorCollection' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.'

I noticed in the [Codegarden 2021 demo](https://www.youtube.com/watch?v=2dm5YgDQVK4), the demo site is using 9.0.0-beta003, so I'm guessing it's only compatible with that.

**Comment by andrewmckaskill** [comment]
This has been resolved and the package is now compiling successfully (and released) for v9. 

https://github.com/umbraco-community/umbraco-graphql/commit/25b84305c4dc486daa446031e6e872832c8f1f95
