### ISSUE TITLE
Do we need to worry about domains?

### ISSUE THREAD

**Issue by PeteDuncanson** [rasmusjp/umbraco-graphql#8]
A little early to be worrying about this now but something that might need some thought. If I bind a node to a domain and then hit that domain's GraphQL endpoint do I only get back that domains data or can I traverse the whole tree and other root nodes?

**Comment by rasmusjp** [comment]
One way to handle this could be by adding some new fields to the root query e.g.

`site: PublishedContent`: the "site" content (where the domain is configured) 
`contentByUrl(url: String!): PublishedContent`: found by url, restricted to the "site" 

That way you'll still be able to get all the content at root by using `contentAtRoot`

**Comment by PeteDuncanson** [comment]
PR for this is open https://github.com/rasmusjp/umbraco-graphql/pull/23
